package org.example.view;

import java.awt.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javaswingdev.drawer.DrawerController;
import javaswingdev.drawer.Drawer;
import javax.swing.*;
import org.example.modelo.Congestionamiento;
import org.example.modelo.FilesControl;
import org.example.modelo.Grafico;
import org.example.modelo.estructuras.Grafo;

/**
 *
 * @author giovanic
 */
public class PrincipalFr extends javax.swing.JFrame {

    private final FilesControl control;
    public DrawerController drawer;
    private final PanelOption po;
    private static final String RUTA = "example/mapa.png";
    private Grafo grafo;

    /**
     * Creates new form PrincipalFr
     */
    public PrincipalFr() {
        initComponents();
        setTitle("MAPS");
        control = new FilesControl();
        control.eliminarArchivo(RUTA);

        Image icon = new ImageIcon(getClass().getResource("/icons/mapa.png")).getImage();
        setIconImage(icon);
        po = new PanelOption();
        po.setTxtArea(jTextArea1);
        po.setPadre(this);

        initReloj();

        drawer = Drawer.newDrawer(this)
                .leftDrawer(true)
                .drawerWidth(285)
                .drawerBackground(Color.WHITE)
                .addChild(po)
                .build();
    }

    private void loadImage(String ruta) {
        Icon icon = new ImageIcon(RUTA);
        imagen.setIcon(icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        opciones = new javax.swing.JButton();
        etiquetaHora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        scrollPane = new javax.swing.JScrollPane();
        imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCargarArchivo = new javax.swing.JMenuItem();
        btnTrafico = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        masZ = new javax.swing.JMenu();
        minZ = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setMinimumSize(new java.awt.Dimension(450, 604));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 604));

        opciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/configs.png"))); // NOI18N
        opciones.setMaximumSize(new java.awt.Dimension(40, 40));
        opciones.setMinimumSize(new java.awt.Dimension(40, 40));
        opciones.setPreferredSize(new java.awt.Dimension(40, 40));
        opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesActionPerformed(evt);
            }
        });

        etiquetaHora.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        etiquetaHora.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaHora.setText("Hora");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrollPane.setViewportView(imagen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPane)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/carpeta.png"))); // NOI18N

        btnCargarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagen.png"))); // NOI18N
        btnCargarArchivo.setText("Cargar Mapa");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(btnCargarArchivo);

        btnTrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/semaforos.png"))); // NOI18N
        btnTrafico.setText("Añadir Trafico");
        btnTrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraficoActionPerformed(evt);
            }
        });
        jMenu1.add(btnTrafico);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        masZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/acercar.png"))); // NOI18N
        masZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masZMouseClicked(evt);
            }
        });
        jMenuBar1.add(masZ);

        minZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/alejar.png"))); // NOI18N
        minZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minZMouseClicked(evt);
            }
        });
        jMenuBar1.add(minZ);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initReloj() {
        // El formato es HH:mm:ss
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");

        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        etiquetaHora.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
    }

    private void opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesActionPerformed
        showDrawer();
    }//GEN-LAST:event_opcionesActionPerformed

    public void showDrawer() {
        if (drawer.isShow()) {
            drawer.hide();
        } else {
            drawer.show();
        }
    }
    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        System.out.println("SALE UN FILECHOOSER");
        control.eliminarArchivo("example/mapa.png");

        grafo = control.leerMapa();
        if (grafo != null) {
            po.setGrafo(grafo);

            Grafico gf = new Grafico();
            po.actualizarComponentes(grafo.getVertices());

            gf.writerDot(gf.getValue(grafo.getArcos()));
            gf.graphvizJava("example/mapa.dot", "example/mapa.png");

            Runnable runnable = new Runnable() {
                @Override
                public void run() {
                    while (!control.existencia("example/mapa.png")) {
                        try {
                            Thread.sleep(900);
                            System.out.println("cargando imagen");
                        } catch (InterruptedException e) {
                        }
                    }
                    actualizarImagen(RUTA);
                }
            };
            Thread hilo = new Thread(runnable);
            hilo.start();
        }
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Seguro que quiere salir?");
        if (i == 0) {
            System.exit(0);//cierra aplicacion
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraficoActionPerformed
        Congestionamiento con = control.leerFileTrafico();
        for (var o : con.getTraficos()) {
            System.out.println(o.toString());
        }
    }//GEN-LAST:event_btnTraficoActionPerformed

    private void minZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minZMouseClicked
        if (control.existencia(RUTA)) {
            Image img = new ImageIcon(RUTA).getImage();
            Image zoom = img.getScaledInstance(imagen.getWidth() - 100, imagen.getHeight() - 100, Image.SCALE_SMOOTH);
            imagen.setIcon(new ImageIcon(zoom));
        }
    }//GEN-LAST:event_minZMouseClicked

    private void masZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masZMouseClicked
        if (control.existencia(RUTA)) {
            Image img = new ImageIcon(RUTA).getImage();
            Image zoom = img.getScaledInstance(imagen.getWidth() + 100, imagen.getHeight() + 100, Image.SCALE_SMOOTH);
            imagen.setIcon(new ImageIcon(zoom));
        }
    }//GEN-LAST:event_masZMouseClicked

    private void actualizarImagen(String path) {
        ImageIcon icono = new ImageIcon(path);
        icono.getImage().flush(); // Forzar la actualización de la caché
        Image img = icono.getImage();
        icono = new ImageIcon(img);
        imagen.setIcon(icono);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCargarArchivo;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnTrafico;
    private javax.swing.JLabel etiquetaHora;
    private javax.swing.JLabel imagen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu masZ;
    private javax.swing.JMenu minZ;
    private javax.swing.JButton opciones;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
