package org.example.view;

import java.awt.Color;
import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javaswingdev.drawer.DrawerController;
import javaswingdev.drawer.Drawer;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.example.modelo.FilesControl;
import org.example.modelo.Grafico;
import org.example.modelo.estructuras.GrafoDirigido;

/**
 *
 * @author giovanic
 */
public class PrincipalFr extends javax.swing.JFrame {

    public DrawerController drawer;
    private final PanelOption po;
    private static final String RUTA = "/home/giovanic/practicagit/final edd/project_final_edd/project_edd_final/example/ej.png";

    /**
     * Creates new form PrincipalFr
     */
    public PrincipalFr() {
        initComponents();
        setTitle("MAPS");
        Image icon = new ImageIcon(getClass().getResource("/icons/mapa.png")).getImage();
        setIconImage(icon);
        po = new PanelOption();

        initReloj();

        drawer = Drawer.newDrawer(this)
                .leftDrawer(true)
                .drawerWidth(285)
                .drawerBackground(Color.WHITE)
                .addChild(po)
                .build();
    }

    private void loadImage(String ruta) {
        //        jTextPane1.setContentType("text/html");
        //        jTextPane1.setText("<html><img src='"
        //                + ruta
        //                + "' \"width=\"" + (jTextPane1.getWidth() - 15)
        //                + "\" height=\"auto\" "
        //                + "/></html>");
        jTextPane1.setText(" ");
        Icon icon = new ImageIcon(RUTA);
        jTextPane1.insertIcon(icon);
        jTextPane1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        opciones = new javax.swing.JButton();
        etiquetaHora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCargarArchivo = new javax.swing.JMenuItem();
        btnRecargarImg = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setMinimumSize(new java.awt.Dimension(450, 604));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 604));

        opciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu-hamburguesa.png"))); // NOI18N
        opciones.setMaximumSize(new java.awt.Dimension(40, 40));
        opciones.setMinimumSize(new java.awt.Dimension(40, 40));
        opciones.setPreferredSize(new java.awt.Dimension(40, 40));
        opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesActionPerformed(evt);
            }
        });

        etiquetaHora.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        etiquetaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaHora.setText("Hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(557, Short.MAX_VALUE))
        );

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        btnCargarArchivo.setText("Cargar Archivo");
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(btnCargarArchivo);

        btnRecargarImg.setText("Recargar Img");
        btnRecargarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarImgActionPerformed(evt);
            }
        });
        jMenu1.add(btnRecargarImg);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initReloj() {
        // El formato es HH:mm:ss
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");

        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        etiquetaHora.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
    }

    private void opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesActionPerformed
        if (drawer.isShow()) {
            drawer.hide();
        } else {
            drawer.show();
        }
    }//GEN-LAST:event_opcionesActionPerformed

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
        System.out.println("SALE UN FILECHOOSER");
        FilesControl control = new FilesControl();
        GrafoDirigido grafo = control.leerMapa();
        if (grafo != null) {

            Grafico gf = new Grafico();
            po.actualizarComponentes(grafo.getNodos());

            gf.writerDot(gf.getValue(grafo.getArcos()));
            gf.graphvizJava("example/ejemplo.dot", "example/ej.png");

            Runnable runnable = () -> {
                try {
                    Thread.sleep(3000);
                } catch (InterruptedException e) {
                }
                loadImage(RUTA);
            };
            Thread hilo = new Thread(runnable);
            hilo.start();
        }
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Seguro que quiere salir?");
        if (i == 0) {
            System.exit(0);//cierra aplicacion
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRecargarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarImgActionPerformed
        loadImage(RUTA);
    }//GEN-LAST:event_btnRecargarImgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCargarArchivo;
    private javax.swing.JMenuItem btnRecargarImg;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JLabel etiquetaHora;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton opciones;
    // End of variables declaration//GEN-END:variables
}
